apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: image-workflow-example
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: http
  to:
    kind: Service
    name: image-workflow-example
