apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-workflow-example
spec:
  rules:
  - host: "image-workflow-example"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: image-workflow-example
            port:
              name: http
