apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-workflow-example
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/larsks/image-workflow-example:v0
          imagePullPolicy: Always
          ports:
            - name: gunicorn
              containerPort: 8000
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
